# Default values for ai-event-concepter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: false

server:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/server
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

client:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
