# Default values for ai-event-concepter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: false

gateway:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/gateway
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker
    - name: USER_SERVICE_URL
      value: http://user-svc:8080
    - name: CONCEPT_SERVICE_URL
      value: http://concept-svc:8080
    - name: GENAI_SERVICE_URL
      value: http://genai-svc:8083

client:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  replicaCount: 1

usersvc:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/user-svc
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://user-svc-db:5432/eventdb
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: postgres
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: SPRING_JPA_SHOW_SQL
      value: "true"
    - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
      value: "true"

conceptsvc:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/concept-svc
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: docker

genaisvc:
  image:
    repository: ghcr.io/aet-devops25/team-git-push-force/genai-svc
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083
    targetPort: 8083
  replicaCount: 1
  env:
    - name: FLASK_ENV
      value: production

userdb:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: eventdb

ingress:
  enabled: true
  className: "nginx"
  tls: true
  host: "dev-aieventconcepter.student.k8s.aet.cit.tum.de"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
