apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: team-git-push-force-monitor
  labels:
    app: alertmanager
data:
  alertmanager.yml: |-
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'teamgitpushforce@gmail.com'
            from: 'teamgitpushforce@gmail.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'teamgitpushforce@gmail.com'
            auth_password: 'prqouryspbzvtrao'
            auth_identity: 'teamgitpushforce@gmail.com'
            require_tls: true
    route:
      receiver: 'email-notifications'