apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-email-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: alertmanager
type: Opaque
data:
  auth_password: {{ .Values.alertmanager.email.auth_password | b64enc | quote }}
