apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace.name }}
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: {{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: email-secret-volume
              mountPath: /etc/alertmanager/secrets
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: email-secret-volume
          secret:
            secretName: alertmanager-email-secret
