apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace.name }}
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      protocol: TCP
      
  selector:
    app: alertmanager
