{{- if .Values.alertmanager.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-ingress
  labels:
    app: alertmanager
  annotations:
    {{- toYaml .Values.alertmanager.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.alertmanager.ingress.className }}
  {{- if .Values.alertmanager.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.alertmanager.ingress.host }}
      secretName: alertmanager-tls
  {{- end }}
  rules:
    - host: {{ .Values.alertmanager.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
{{- end }} 