apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-user-db-service-monitor
  labels:
    app: prometheus
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - team-git-push-force-monitor
  selector:
    matchLabels:
      app: postgres-exporter-user-db
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-concept-db-service-monitor
  labels:
    app: prometheus
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - team-git-push-force-monitor
  selector:
    matchLabels:
      app: postgres-exporter-concept-db
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-service-monitor
  labels:
    app: prometheus
spec:
  endpoints:
  - port: http-metrics
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_app]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_managed_by]
      targetLabel: managed_by
  namespaceSelector:
    matchNames:
    - team-git-push-force-monitor
  selector:
    matchLabels:
      app: redis-exporter