apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: team-git-push-force-monitoring
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.team-git-push-force-monitoring.svc.cluster.local:9090
        isDefault: true 