# Grafana Datasource Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
---
# Grafana Dashboard Provider Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
# Grafana Application Dashboard
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-sample-dashboard
  labels:
    grafana_dashboard: "1"
data:
  ai-event-concepter-dashboard.json: |
    {
      "id": null,
      "title": "AI Event Concepter - Application Overview",
      "uid": "ai-event-concepter",
      "tags": [
        "ai-event-concepter",
        "microservices",
        "monitoring"
      ],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Service Health Overview",
          "type": "stat",
          "targets": [
            {
              "expr": "up",
              "legendFormat": "{{"{{"}}service{{"}}"}} ({{"{{"}}job{{"}}"}})",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "thresholds": {
                "steps": [
                  {
                    "color": "red",
                    "value": 0
                  },
                  {
                    "color": "green",
                    "value": 1
                  }
                ]
              }
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Request Rate",
          "type": "graph",
          "targets": [
            {
              "expr": "sum by (service, method, uri) (rate(http_server_requests_seconds_count[5m]))",
              "legendFormat": "{{"{{"}}service{{"}}"}} - {{"{{"}}method{{"}}"}} {{"{{"}}uri{{"}}"}}",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "Response Time (95th percentile)",
          "type": "graph",
          "targets": [
            {
              "expr": "histogram_quantile(0.95, sum by (le, service) (rate(http_server_requests_seconds_bucket[5m])))",
              "legendFormat": "{{"{{"}}service{{"}}"}}",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "id": 4,
          "title": "Error Rate",
          "type": "graph",
          "targets": [
            {
              "expr": "sum by (service) (rate(http_server_requests_seconds_count{status=~\"5..\"}[5m]))",
              "legendFormat": "{{"{{"}}service{{"}}"}} - 5xx errors",
              "datasource": "Prometheus"
            },
            {
              "expr": "sum by (service) (rate(http_server_requests_seconds_count{status=~\"4..\"}[5m]))",
              "legendFormat": "{{"{{"}}service{{"}}"}} - 4xx errors",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        },
        {
          "id": 5,
          "title": "Memory Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "jvm_memory_used_bytes / jvm_memory_max_bytes * 100",
              "legendFormat": "{{"{{"}}service{{"}}"}} - {{"{{"}}area{{"}}"}}",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 16
          }
        },
        {
          "id": 6,
          "title": "CPU Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(process_cpu_seconds_total[5m]) * 100",
              "legendFormat": "{{"{{"}}service{{"}}"}}",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 16
          }
        },
        {
          "id": 7,
          "title": "Database Connections",
          "type": "graph",
          "targets": [
            {
              "expr": "hikaricp_connections_active",
              "legendFormat": "{{"{{"}}service{{"}}"}} - Active",
              "datasource": "Prometheus"
            },
            {
              "expr": "hikaricp_connections_idle",
              "legendFormat": "{{"{{"}}service{{"}}"}} - Idle",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 24
          }
        },
        {
          "id": 8,
          "title": "Service Version Overview",
          "type": "table",
          "targets": [
            {
              "expr": "app_version_info",
              "format": "table",
              "refId": "A"
            }
          ],
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {}
            }
          ],
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 32
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "30s"
    }
---
# Grafana Infrastructure Dashboard
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-infrastructure-dashboards
  labels:
    app: grafana
    grafana_dashboard: "1"
data:
  infrastructure-dashboard.json: |
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "8.0.0"
        },
        {
          "type": "datasource",
          "id": "prometheus",
          "name": "Prometheus",
          "version": "1.0.0"
        }
      ],
      "id": null,
      "title": "AI Event Concepter - Infrastructure Overview",
      "uid": "ai-event-concepter-infrastructure",
      "tags": [
        "ai-event-concepter",
        "infrastructure",
        "system",
        "monitoring"
      ],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Node CPU Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
              "legendFormat": "{{`{{`}}instance{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent",
              "min": 0,
              "max": 100
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Node Memory Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
              "legendFormat": "{{`{{`}}instance{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent",
              "min": 0,
              "max": 100
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "Disk Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - {{`{{`}}mountpoint{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent",
              "min": 0,
              "max": 100
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "id": 4,
          "title": "Network Traffic",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(node_network_receive_bytes_total[5m])",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - {{`{{`}}device{{`}}`}} - RX",
              "datasource": "Prometheus"
            },
            {
              "expr": "rate(node_network_transmit_bytes_total[5m])",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - {{`{{`}}device{{`}}`}} - TX",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "bytes"
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        },
        {
          "id": 5,
          "title": "Container CPU Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(container_cpu_usage_seconds_total{container!=\"\"}[5m]) * 100",
              "legendFormat": "{{`{{`}}name{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent"
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 16
          }
        },
        {
          "id": 6,
          "title": "Container Memory Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "container_memory_usage_bytes{container!=\"\"}",
              "legendFormat": "{{`{{`}}name{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "bytes"
            }
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 16
          }
        },
        {
          "id": 7,
          "title": "PostgreSQL Active Connections",
          "type": "graph",
          "targets": [
            {
              "expr": "pg_stat_database_numbackends",
              "legendFormat": "{{`{{`}}datname{{`}}`}}",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 24
          }
        },
        {
          "id": 8,
          "title": "PostgreSQL Transaction Rate",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(pg_stat_database_xact_commit[5m])",
              "legendFormat": "{{`{{`}}datname{{`}}`}} - Commits",
              "datasource": "Prometheus"
            },
            {
              "expr": "rate(pg_stat_database_xact_rollback[5m])",
              "legendFormat": "{{`{{`}}datname{{`}}`}} - Rollbacks",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 24
          }
        },
        {
          "id": 9,
          "title": "System Load Average",
          "type": "graph",
          "targets": [
            {
              "expr": "node_load1",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - 1m",
              "datasource": "Prometheus"
            },
            {
              "expr": "node_load5",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - 5m",
              "datasource": "Prometheus"
            },
            {
              "expr": "node_load15",
              "legendFormat": "{{`{{`}}instance{{`}}`}} - 15m",
              "datasource": "Prometheus"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 32
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "30s"
    } 