apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: team-git-push-force-monitoring
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
      protocol: TCP
      name: http
  selector:
    app: grafana 