apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sidecar
  labels:
    app: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-sidecar-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-sidecar-rolebinding
subjects:
- kind: ServiceAccount
  name: grafana-sidecar
  namespace: team-git-push-force-dev
roleRef:
  kind: Role
  name: grafana-sidecar-role
  apiGroup: rbac.authorization.k8s.io 