{{- if .Values.prometheus.ingress.enabled }}
---
# Prometheus Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:
    {{- $annotations := .Values.prometheus.ingress.annotations | default dict }}
    {{- if $annotations }}
    {{- toYaml $annotations | nindent 4 }}
    {{- end }}
    # Ensure this Ingress is created after the prometheus service
    "helm.sh/hook-weight": "1"
spec:
  {{- if .Values.prometheus.ingress.className }}
  ingressClassName: {{ .Values.prometheus.ingress.className }}
  {{- end }}
  {{- if .Values.prometheus.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.prometheus.ingress.host }}"
      secretName: "prometheus-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.prometheus.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
{{- end }}
{{- if .Values.alertmanager.ingress.enabled }}
---
# Alertmanager Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager-ingress
  labels:
    app: alertmanager
  annotations:
    {{- toYaml .Values.alertmanager.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.alertmanager.ingress.className }}
  {{- if .Values.alertmanager.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.alertmanager.ingress.host }}
      secretName: alertmanager-tls
  {{- end }}
  rules:
    - host: {{ .Values.alertmanager.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
{{- end }} 