apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-access
  namespace: team-git-push-force-dev
spec:
  podSelector: {}  # Apply to all pods in the namespace
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: team-git-push-force-monitor
    ports:
    - protocol: TCP
      port: 8080  # Spring Boot Actuator
    - protocol: TCP
      port: 8083  # GenAI service
    - protocol: TCP
      port: 5432  # PostgreSQL
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-egress
  namespace: team-git-push-force-monitor
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: team-git-push-force-dev
    ports:
    - protocol: TCP
      port: 8080  # Spring Boot services
    - protocol: TCP
      port: 8083  # GenAI service
    - protocol: TCP
      port: 5432  # PostgreSQL
  - to: []  # Allow DNS resolution and other necessary egress
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53 