apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: team-git-push-force-monitor
  labels:
    app: node-exporter
    monitoring: "true"
spec:
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP