apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  labels:
    app: postgres-exporter
spec:
  type: ClusterIP
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
      name: metrics
  selector:
    app: postgres-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          args:
            - "--extend.query-path=/etc/postgres_exporter/queries.yaml"
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:password@postgres:5432/postgres?sslmode=disable"
          ports:
            - containerPort: 9187
          volumeMounts:
            - name: postgres-exporter-config
              mountPath: /etc/postgres_exporter/
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: postgres-exporter-config
          configMap:
            name: postgres-exporter-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter-config
  labels:
    app: postgres-exporter
data:
  queries.yaml: |
    pg_replication:
      query: "SELECT CASE WHEN NOT pg_is_in_recovery() THEN 0 ELSE GREATEST (0, EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))) END AS lag"
      master: true
      metrics:
        - lag:
            usage: "GAUGE"
            description: "Replication lag behind master in seconds" 