apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: client-svc
  namespace: team-git-push-force-monitor
spec:
  jobName: client-svc
  interval: 30s
  module: http_2xx
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.team-git-push-force-monitor.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://client-svc.team-git-push-force-dev.svc.cluster.local/auth/login