apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: "ai-event-concepter"
        environment: "development"

    rule_files:
      - "rules/*.yml"

    # ServiceMonitor discovery is handled automatically by Prometheus Operator
    # No need for manual scrape_configs when using ServiceMonitors
    scrape_configs:
      # Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
        metrics_path: '/metrics'
        scrape_interval: 15s

      # Node Exporter for system metrics (if deployed)
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - team-git-push-force-monitor
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: node-exporter
        - target_label: monitoring
          replacement: "true"

      {{- if .Values.cadvisor.enabled }}
      # cAdvisor for container metrics (if deployed)
      - job_name: 'cadvisor'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - team-git-push-force-monitor
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: cadvisor
        - target_label: monitoring
          replacement: "true"
      {{- end }}

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093