apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: team-git-push-force-monitoring
  labels:
    app: prometheus
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: web
  selector:
    app: prometheus