{{- if .Values.prometheus.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: team-git-push-force-monitoring
  {{- $annotations := .Values.prometheus.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.prometheus.ingress.className }}
  ingressClassName: {{ .Values.prometheus.ingress.className }}
  {{- end }}
  {{- if .Values.prometheus.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.prometheus.ingress.host }}"
      secretName: "ai-event-concepter-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.prometheus.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
{{- end }}