# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # OpenAPI linting with Redocly
  - repo: https://github.com/Redocly/openapi-cli
    rev: v1.0.0-beta.92
    hooks:
      - id: openapi-cli-lint
        name: Lint OpenAPI specs
        files: api/.*\.yaml$
        args: ["lint"]

  # YAML formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        name: Check YAML syntax
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files

  # Java formatting with Google Java Format
  - repo: https://github.com/google/google-java-format
    rev: v1.16.0
    hooks:
      - id: google-java-format
        name: Format Java code
        files: \.java$

  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Format Python code
        language_version: python3

  # TypeScript/JavaScript formatting with Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        name: Format TypeScript/JavaScript code
        files: \.(ts|js|jsx|tsx)$
        additional_dependencies:
          - prettier@2.8.8

  # Custom hook to run API code generation
  - repo: local
    hooks:
      - id: api-code-generation
        name: Generate code from OpenAPI specs
        entry: ./api/scripts/gen-all.sh
        language: system
        files: api/.*\.yaml$
        pass_filenames: false
        stages: [pre-push]

  # Commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        name: Check commit message format
        stages: [commit-msg]
