services:
  # Client service (Angular frontend)
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - gateway
    networks:
      - frontend-network
      - backend-network

  # API Gateway (Spring Boot)
  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_MAIN_WEB_APPLICATION_TYPE=reactive
      - USER_SERVICE_URL=http://user-svc:8080
      - CONCEPT_SERVICE_URL=http://concept-svc:8080
      - GENAI_SERVICE_URL=http://genai-svc:8083
    depends_on:
      - user-svc
      - concept-svc
      - genai-svc
    networks:
      - backend-network

  # User Service (Spring Boot)
  user-svc:
    build:
      context: ./user-svc
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-svc-db:5432/eventdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    networks:
      - backend-network
    depends_on:
      - user-svc-db

  user-svc-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eventdb
    networks:
      - backend-network
    #volumes:
      #- eventdb_data:/var/lib/postgresql/data

  # Concept Service (Spring Boot)
  concept-svc:
    build:
      context: ./concept-svc
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://concept-svc-db:5432/conceptdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    networks:
      - backend-network
    depends_on:
      - concept-svc-db

  concept-svc-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=conceptdb
    networks:
      - backend-network
    #volumes:
      #- conceptdb_data:/var/lib/postgresql/data

  # GenAI Service (Python Flask)
  genai-svc:
    build:
      context: ./genai-svc
    ports:
      - "8083:8083"
    environment:
      - FLASK_ENV=production
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
