services:
  # Client service (Angular frontend)
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - frontend-network
      - backend-network

  # API Gateway (Spring Boot)
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - USER_SERVICE_URL=http://user-svc:8080
      - CONCEPT_SERVICE_URL=http://concept-svc:8080
      - GENAI_SERVICE_URL=http://genai-svc:8083
    depends_on:
      - user-svc
      - concept-svc
      - genai-svc
    networks:
      - backend-network

  # User Service (Spring Boot)
  user-svc:
    build:
      context: ./user-svc
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend-network

  # Concept Service (Spring Boot)
  concept-svc:
    build:
      context: ./concept-svc
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend-network

  # GenAI Service (Python Flask)
  genai-svc:
    build:
      context: ./genai-svc
    ports:
      - "8083:8083"
    environment:
      - FLASK_ENV=production
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge