global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "ai-event-concepter"
    environment: "development"

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Spring Boot Services with Actuator endpoints
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'gateway:8080'
        - 'user-svc:8080'
        - 'concept-svc:8080'
        - 'genai-svc:8083'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: service
      - source_labels: [__address__]
        regex: '([^:]+):.*'
        target_label: app
      - target_label: monitoring
        replacement: "true"
      - target_label: environment
        replacement: "development"

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - target_label: monitoring
        replacement: "true"

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - target_label: monitoring
        replacement: "true"

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - target_label: monitoring
        replacement: "true"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration for persistence
# Note: Storage settings are configured via command line arguments in docker-compose.yml 