{
 "title": "Sample Dashboard",
 "description": "This is a simple dashboard to show basic metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Process Virtual Memory Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Application Ready Time Seconds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "application_ready_time_seconds" }
   ]
  },
  {
   "title": "HTTP Server Requests Active Seconds Max",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_active_seconds_max"
    }
   ]
  }
 ]
}