apiVersion: v1
kind: Service
metadata:
  name: client-svc
  labels:
    app: client
    monitoring: "true"
spec:
  selector:
    app: ai-event-concepter-client-selector
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.client.service.type }}
