apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  selector:
    app: ai-event-concepter-client-selector
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}
