apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-event-concepter-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: ai-event-concepter-client-selector
  template:
    metadata:
      labels:
        app: ai-event-concepter-client-selector
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            - name: PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api_url
