apiVersion: v1
kind: Service
metadata:
  name: concept-svc
  labels:
    app: concept-svc
    monitoring: "true"
spec:
  selector:
    app: ai-event-concepter-concept-svc-selector
  ports:
    - port: {{ .Values.conceptsvc.service.port }}
      targetPort: {{ .Values.conceptsvc.service.targetPort }}
      protocol: TCP
  type: {{ .Values.conceptsvc.service.type }}
