apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    monitoring: "true"
spec:
  selector:
    app: ai-event-concepter-gateway-selector
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.gateway.service.type }}
