apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-event-concepter-gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: ai-event-concepter-gateway-selector
  template:
    metadata:
      labels:
        app: ai-event-concepter-gateway-selector
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.gateway.service.targetPort }}
          env:
            {{- range .Values.gateway.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}