apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: ai-event-concepter-gateway-selector
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
      protocol: TCP
  type: {{ .Values.gateway.service.type }}
