apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  selector:
    app: ai-event-concepter-genai-svc-selector
  ports:
    - port: {{ .Values.genaisvc.service.port }}
      targetPort: {{ .Values.genaisvc.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genaisvc.service.type }}
