apiVersion: v1
kind: Service
metadata:
  name: genai-svc
  labels:
    app: genai-svc
    monitoring: "true"
spec:
  selector:
    app: ai-event-concepter-genai-svc-selector
  ports:
    - port: {{ .Values.genaisvc.service.port }}
      targetPort: {{ .Values.genaisvc.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.genaisvc.service.type }}
