{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ai-event-concepter-ingress"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.ingress.host }}"
      secretName: "ai-event-concepter-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: {{ .Values.gateway.service.port }}
{{- end }}
