{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/NetworkPolicy" }}
# Network policy for client (frontend)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: client-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-client-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from: []  # Allow ingress traffic from anywhere (for user access)
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-gateway-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-gateway-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-client-selector
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-user-svc-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-concept-svc-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for genai-svc
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: genai-svc-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-genai-svc-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-gateway-selector
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-weaviate-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-minio-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-concept-svc-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # Allow outbound internet access for Hugging Face models
  - to: []
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
---
# Network policy for weaviate
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: genai-svc-weaviate-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-genai-svc-weaviate-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-selector
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    ports:
    - port: 8080
      protocol: TCP
    - port: 50051
      protocol: TCP
    ports:
    - port: 8080
      protocol: TCP
    - port: 50051
      protocol: TCP
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-t2v-transformers-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for t2v-transformers
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: genai-svc-t2v-transformers-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-genai-svc-t2v-transformers-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-weaviate-selector
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # Allow outbound internet access for Hugging Face models
  - to: []
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
---
# Network policy for minio
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: genai-svc-minio-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-genai-svc-minio-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-selector
---
# Network policy for concept-svc
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: concept-svc-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-concept-svc-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-gateway-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-genai-svc-selector
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-concept-svc-db-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-user-svc-db-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for concept-svc-db
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: concept-svc-db-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-concept-svc-db-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-concept-svc-selector
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for user-svc
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-svc-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-user-svc-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-gateway-selector
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-user-svc-db-selector
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# Network policy for user-svc-db
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-svc-db-network-policy
spec:
  podSelector:
    matchLabels:
      app: ai-event-concepter-user-svc-db-selector
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ai-event-concepter-user-svc-selector
    - podSelector:
        matchLabels:
          app: ai-event-concepter-concept-svc-selector
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}
