apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-db-postgres-exporter
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:postgres@third-db:5432/third_db_name?sslmode=disable" # Update as needed
---
apiVersion: v1
kind: Service
metadata:
  name: third-db-postgres-exporter
  labels:
    app: postgres-exporter
    monitoring: "true"
spec:
  selector:
    app: postgres-exporter
  ports:
    - name: postgres-exporter
      port: 9187
      targetPort: 9187
  type: ClusterIP 