apiVersion: v1
kind: Service
metadata:
  name: user-svc
  labels:
    app: user-svc
    monitoring: "true"
spec:
  selector:
    app: ai-event-concepter-user-svc-selector
  ports:
    - port: {{ .Values.usersvc.service.port }}
      targetPort: {{ .Values.usersvc.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.usersvc.service.type }}
