apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-event-concepter-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: ai-event-concepter-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.dev-aieventconcepter.student.k8s.aet.cit.tum.de
    - prometheus.dev-aieventconcepter.student.k8s.aet.cit.tum.de 