ingress:
  enabled: true
  className: "nginx"
  tls: true
  host: grafana.dev-aieventconcepter.student.k8s.aet.cit.tum.de
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Removed for manual certificate management
    kubernetes.io/ingress.class: nginx
    # Add any other required annotations here

grafana:
  image:
    repository: grafana/grafana
    tag: 10.1.5 # Use the latest stable version as needed
  adminUser: admin # Change for production
  adminPassword: strongpassword # Change for production
  service:
    type: ClusterIP
    port: 3000
  resources: {}
  persistence:
    enabled: false # Set to true and configure storageClassName for persistent storage
    size: 5Gi
    storageClassName: ""
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  rbac:
    create: false
  serviceAccount:
    create: false

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.45.0 # Use the latest stable version as needed
  serviceAccount:
    create: false
    name: default
  resources: {}
  persistence:
    enabled: false # Set to true and configure storageClassName for persistent storage
    size: 5Gi
    storageClassName: ""
  server:
    service:
      port: 9090
    rbac:
      create: false
    serviceAccount:
      create: false
  ingress:
    enabled: true
    className: "nginx"
    tls: true
    host: prometheus.dev-aieventconcepter.student.k8s.aet.cit.tum.de
    annotations:
      # cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Removed for manual certificate management
      kubernetes.io/ingress.class: nginx
