name: Deploy to Staging Kubernetes

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  generate_api_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install OpenAPI Generator
        run: |
          npm install -g @openapitools/openapi-generator-cli
          pip install openapi-python-client

      - name: Generate Code
        run: |
          chmod +x api/scripts/gen-all.sh
          ./api/scripts/gen-all.sh

      - name: Upload entire repository as artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-repository
          path: .

  build_images:
    runs-on: ubuntu-latest
    needs: generate_api_code
    strategy:
      matrix:
        service: [client, gateway, user-svc, concept-svc, genai-svc]
      max-parallel: 1
    steps:
      - name: Download full repository artifact
        uses: actions/download-artifact@v4
        with:
          name: full-repository
          path: .

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }},enable=${{ github.event_name == 'pull_request' }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.service }}
          cache-to: type=gha,scope=${{ matrix.service }},mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build_images
    environment:
      name: staging

    steps:
      - name: Download full repository artifact
        uses: actions/download-artifact@v4
        with:
          name: full-repository
          path: .

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Run Helm Upgrade
        run: |
          cd helm/ai-event-concepter
          helm upgrade --install ai-event-concepter . \
            --namespace team-git-push-force-dev \
            --create-namespace \
            --set ingress.host=dev-aieventconcepter.student.k8s.aet.cit.tum.de \
            --set client.image.tag=pr-${{ github.event.pull_request.number || github.sha }} \
            --set gateway.image.tag=pr-${{ github.event.pull_request.number || github.sha }} \
            --set usersvc.image.tag=pr-${{ github.event.pull_request.number || github.sha }} \
            --set conceptsvc.image.tag=pr-${{ github.event.pull_request.number || github.sha }} \
            --set genaisvc.image.tag=pr-${{ github.event.pull_request.number || github.sha }}

      - name: Rollout Restart Deployments
        run: |
          kubectl rollout restart deployment -n team-git-push-force-dev
