name: Deploy Monitoring Stack

on:
  workflow_dispatch:  # You can also trigger on push, schedule, etc.

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Create/Update Alertmanager config secret
        run: |
          kubectl create secret generic alertmanager-main \
            --from-file=alertmanager.yaml=monitoring/alertmanager.yml \
            -n team-git-push-force-monitoring --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Prometheus
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace team-git-push-force-monitoring --create-namespace \
            -f helm/ai-event-concepter/prometheus-values.yaml

      - name: Deploy Grafana
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm upgrade --install grafana grafana/grafana \
            --namespace team-git-push-force-monitoring  \
            -f helm/ai-event-concepter/grafana-values.yaml
