name: Deploy to Production Kubernetes

on:
  workflow_run:
    workflows: [Build Docker Images]
    types:
      - completed
    branches:
      - main
    conclusion: success

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Run Helm
        run: |
          cd helm/ai-event-concepter
          helm upgrade --debug --install -n team-git-push-force ai-event-concepter . \
            --set ingress.host=${{ inputs.ingress_host || 'aieventconcepter.student.k8s.aet.cit.tum.de' }}
          kubectl rollout restart deployment -n team-git-push-force
